FROM maven:3.5-jdk-8-alpine
COPY pom.xml /pom.xml
COPY src /src
RUN mkdir /build
RUN mkdir /target
RUN mkdir /classes
RUN ln -s /build/target /target
RUN ln -s /build/classes /classes
RUN mvn dependency:copy-dependencies
RUN cp -r /target/dependency /usr/share/maven/ref/repository
CMD mvn package -o
